// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/monitoring-service/src/entity"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// MonitorService mocks base method.
func (m *MockService) MonitorService(ctx context.Context, url string) (entity.ServiceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MonitorService", ctx, url)
	ret0, _ := ret[0].(entity.ServiceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MonitorService indicates an expected call of MonitorService.
func (mr *MockServiceMockRecorder) MonitorService(ctx, url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MonitorService", reflect.TypeOf((*MockService)(nil).MonitorService), ctx, url)
}
