// Code generated by MockGen. DO NOT EDIT.
// Source: metric.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPublisher is a mock of Publisher interface.
type MockPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMockRecorder
}

// MockPublisherMockRecorder is the mock recorder for MockPublisher.
type MockPublisherMockRecorder struct {
	mock *MockPublisher
}

// NewMockPublisher creates a new mock instance.
func NewMockPublisher(ctrl *gomock.Controller) *MockPublisher {
	mock := &MockPublisher{ctrl: ctrl}
	mock.recorder = &MockPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisher) EXPECT() *MockPublisherMockRecorder {
	return m.recorder
}

// PublishResponseStatus mocks base method.
func (m *MockPublisher) PublishResponseStatus(label string, val int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PublishResponseStatus", label, val)
}

// PublishResponseStatus indicates an expected call of PublishResponseStatus.
func (mr *MockPublisherMockRecorder) PublishResponseStatus(label, val interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishResponseStatus", reflect.TypeOf((*MockPublisher)(nil).PublishResponseStatus), label, val)
}

// PublishResponseTime mocks base method.
func (m *MockPublisher) PublishResponseTime(label string, duration int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PublishResponseTime", label, duration)
}

// PublishResponseTime indicates an expected call of PublishResponseTime.
func (mr *MockPublisherMockRecorder) PublishResponseTime(label, duration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishResponseTime", reflect.TypeOf((*MockPublisher)(nil).PublishResponseTime), label, duration)
}
